import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ApolloGQLProvider } from "@web/utils/apollo/apollo.provider";
import {
  ColorSchemeScript,
  MantineProvider,
  createTheme,
  mantineHtmlProps,
} from "@mantine/core";

import "./globals.css";
import "@mantine/core/styles.css";
import "@mantine/dropzone/styles.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = createTheme({
  /** Put your mantine theme override here */
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ApolloGQLProvider>
          <MantineProvider theme={theme}>{children}</MantineProvider>
        </ApolloGQLProvider>
      </body>
    </html>
  );
}
