import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import { ApolloGQLProvider } from "@web/utils/apollo/apollo.provider";
import {
  ColorSchemeScript,
  MantineProvider,
  createTheme,
  mantineHtmlProps,
} from "@mantine/core";
import "./globals.css";
import "@mantine/core/styles.css";
import "@mantine/dropzone/styles.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = createTheme({
  fontFamily: poppins.style.fontFamily,

});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body
        className={` ${poppins.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <ApolloGQLProvider>
          <MantineProvider theme={theme}>{children}</MantineProvider>
        </ApolloGQLProvider>
      </body>
    </html>
  );
}
