mutation AskQuestionJobAnswer($input: AskQuestionJobAnswerRequest!) {
  askQuestion(input: $input) {
    createdAt
    id
    jobId
    question
    type
    updatedAt
    content {
      content
      chats {
        content
        role
      }
    }
  }
}
