query GetMockInterviewSessionQuestions(
  $input: GetMockInterviewSessionQuestionRequest!
) {
  getMockInterviewSessionQuestions(input: $input) {
    endTime
    id
    mockInterviewSessionId
    question
    startTime
    type
  }
}
